let QUESTIONS=[];let state={mode:'',pool:[],idx:0,graded:false,results:[],exam:null,current:null};
const $=id=>document.getElementById(id);
const PUNCT=/[\s\n\r\t，。！？、；：「」『』（）()\[\]【】《》〈〉,.!?;:'"“”‘’\-—＿_・…~～\/\\|＋+＝=＊*#@％%0-9０-９]/g;
function clean(s){return (s||'').replace(PUNCT,'');}
function esc(s){return String(s).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function loadStore(){return JSON.parse(localStorage.getItem('quizV3')||'{"wrong":[],"stars":[],"stats":{"total":0,"sum":0,"perfect":0,"wrongCount":0,"days":{},"byCat":{},"reports":[],"bestCombo":0}}')}
function saveStore(s){localStorage.setItem('quizV3',JSON.stringify(s));renderHome()}
function today(){return new Date().toISOString().slice(0,10)}
function showPanel(id){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));$(id).classList.add('active'); if(id==='home')renderHome(); if(id==='progress')renderProgress(); if(id==='search')renderSearch(); if(id==='game')newGameQuestion();}
fetch('questions.json').then(r=>r.json()).then(q=>{QUESTIONS=q;renderHome();showPanel('home');}).catch(()=>alert('題庫載入失敗，請確認 questions.json 已上傳'));
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}
$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('dark',document.body.classList.contains('dark')?'1':'0')}; if(localStorage.getItem('dark')==='1')document.body.classList.add('dark');
function renderHome(){let s=loadStore();let avg=s.stats.total?(s.stats.sum/s.stats.total).toFixed(1):'0.0';let wrong=s.wrong.length;let days=Object.keys(s.stats.days||{}).length;$('statsCards').innerHTML=`<div class="statcard">累積作答<br><b>${s.stats.total||0}</b></div><div class="statcard">平均分數<br><b>${avg}</b></div><div class="statcard">滿分題數<br><b>${s.stats.perfect||0}</b></div><div class="statcard">錯題庫<br><b>${wrong}</b></div><div class="statcard">學習天數<br><b>${days}</b></div>`}
function startSequential(cat,a,b){let pool=QUESTIONS.filter(x=>x.category===cat&&x.number>=a&&x.number<=b);startQuiz(`循序練習 ${pool[0]?.categoryName||''} ${a}-${b}`,pool,false)}
function startMixed20(){let pool=QUESTIONS.filter(x=>(x.category==='army'&&x.number<=20)||(x.category==='staff'&&x.number<=20)||x.category==='intel'||x.category==='combined');startQuiz('隨機20題：各科前段混合',shuffle(pool).slice(0,20),true)}
function startRandom40(){startQuiz('隨機40題：全題庫',shuffle(QUESTIONS).slice(0,40),true)}
function startWrongPractice(){let s=loadStore();if(!s.wrong.length){alert('目前沒有錯題');return}startQuiz('錯題庫複習',s.wrong,false)}
function startExam(stage){let cfg={1:{n:20,pass:95},2:{n:100,pass:97},3:{n:100,pass:99}}[stage];startQuiz(`第${stage}階段模擬考：${cfg.n}題｜合格${cfg.pass}分`,shuffle(QUESTIONS).slice(0,cfg.n),true,{stage,pass:cfg.pass})}
function startQuiz(label,pool,random,exam=null){state={mode:label,pool,idx:0,graded:false,results:[],exam,current:null};showPanel('quiz');$('modeLabel').textContent=label;renderQuestion()}
function renderQuestion(){state.current=state.pool[state.idx];if(!state.current){finishQuiz();return}$('qMeta').textContent=`${state.current.categoryName} 第${state.current.number}題｜${state.idx+1}/${state.pool.length}`;$('qText').textContent=state.current.q;$('answerInput').value='';$('result').classList.add('hidden');$('bar').style.width=`${(state.idx/state.pool.length)*100}%`;state.graded=false;updateStar()}
function nextQuestion(){if(!state.current)return;if(!state.graded && $('answerInput').value.trim()){gradeCurrent()}state.idx++;if(state.idx>=state.pool.length){finishQuiz()}else renderQuestion()}
function finishOrHome(){if(state.results.length){if(confirm('要結束並產生成績單嗎？'))finishQuiz();}else showPanel('home')}
function showStdAnswer(){$('result').classList.remove('hidden');$('result').innerHTML=`<h3>標準答案</h3><p>${esc(state.current.a)}</p><p class="meta">${esc(state.current.source)}</p>`}
function diffAnswer(user,ans){let u=[...clean(user)], a=[...clean(ans)], n=a.length,m=u.length;let dp=Array.from({length:n+1},()=>Array(m+1).fill(0));for(let i=0;i<=n;i++)dp[i][0]=i;for(let j=0;j<=m;j++)dp[0][j]=j;for(let i=1;i<=n;i++)for(let j=1;j<=m;j++){let cost=a[i-1]===u[j-1]?0:1;dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+cost)}let i=n,j=m,ops=[];while(i>0||j>0){if(i>0&&j>0&&a[i-1]===u[j-1]&&dp[i][j]===dp[i-1][j-1]){ops.push({t:'ok',c:a[i-1]});i--;j--}else if(i>0&&j>0&&dp[i][j]===dp[i-1][j-1]+1){ops.push({t:'wrong',exp:a[i-1],got:u[j-1]});i--;j--}else if(i>0&&dp[i][j]===dp[i-1][j]+1){ops.push({t:'miss',c:a[i-1]});i--}else{ops.push({t:'extra',c:u[j-1]});j--}}ops.reverse();let wrong=ops.filter(o=>o.t==='wrong').length,miss=ops.filter(o=>o.t==='miss').length,extra=ops.filter(o=>o.t==='extra').length;let score=Math.max(0,100-(wrong+miss+extra)*0.5);let html=ops.map(o=>o.t==='ok'?`<span class="ok">${esc(o.c)}</span>`:o.t==='miss'?`<span class="miss">${esc(o.c)}</span>`:o.t==='wrong'?`<span class="wrong" title="你寫：${esc(o.got)}，應為：${esc(o.exp)}">${esc(o.exp)}</span>`:`<span class="extra" title="多寫">${esc(o.c)}</span>`).join('');return{score,wrong,miss,extra,html,total:n}}
function gradeCurrent(){let r=diffAnswer($('answerInput').value,state.current.a);state.graded=true;let rec={id:state.current.id,score:r.score,wrong:r.wrong,miss:r.miss,extra:r.extra,cat:state.current.categoryName};state.results[state.idx]=rec;updateStats(state.current,r.score,r);if(r.score<100)addWrong(state.current);$('result').classList.remove('hidden');$('result').innerHTML=`<h3>批改結果：${r.score.toFixed(1)}分</h3><p><span class="pill">錯字 ${r.wrong}</span><span class="pill">漏字 ${r.miss}</span><span class="pill">多字 ${r.extra}</span><span class="pill">扣分 ${((r.wrong+r.miss+r.extra)*0.5).toFixed(1)}</span></p><div class="diff">${r.html}</div><h4>標準答案</h4><p>${esc(state.current.a)}</p>`;$('bar').style.width=`${((state.idx+1)/state.pool.length)*100}%`}
function updateStats(q,score,r){let s=loadStore();let k='g'+q.id+'_'+Date.now();s.stats.total++;s.stats.sum+=score;if(score===100)s.stats.perfect++;else s.stats.wrongCount++;s.stats.days[today()]=(s.stats.days[today()]||0)+1;s.stats.byCat[q.categoryName]=s.stats.byCat[q.categoryName]||{n:0,sum:0};s.stats.byCat[q.categoryName].n++;s.stats.byCat[q.categoryName].sum+=score;saveStore(s)}
function addWrong(q){let s=loadStore();if(!s.wrong.some(x=>x.id===q.id))s.wrong.push(q);saveStore(s)}
function toggleStar(){let s=loadStore();let id=state.current.id;if(s.stars.includes(id))s.stars=s.stars.filter(x=>x!==id);else s.stars.push(id);saveStore(s);updateStar()}
function updateStar(){let s=loadStore();$('starBtn').textContent=s.stars.includes(state.current?.id)?'★ 已收藏':'☆ 收藏'}
function finishQuiz(){let arr=state.results.filter(Boolean);let avg=arr.length?arr.reduce((a,b)=>a+b.score,0)/arr.length:0;let pass=!state.exam||avg>=state.exam.pass;let by={};arr.forEach(x=>{by[x.cat]=by[x.cat]||{n:0,sum:0};by[x.cat].n++;by[x.cat].sum+=x.score});let byHtml=Object.entries(by).map(([k,v])=>`<span class="pill">${k} ${(v.sum/v.n).toFixed(1)}</span>`).join('');let report={date:new Date().toLocaleString(),mode:state.mode,score:+avg.toFixed(1),pass};let s=loadStore();s.stats.reports=(s.stats.reports||[]).slice(-9);s.stats.reports.push(report);saveStore(s);$('result').classList.remove('hidden');$('result').innerHTML=`<div class="report"><h2>成績單</h2><h1 class="${pass?'pass':'fail'}">${avg.toFixed(1)} 分｜${pass?'合格 PASS':'不合格'}</h1><p>模式：${esc(state.mode)}</p><p>題數：${state.pool.length}｜已批改：${arr.length}</p><p>錯字：${arr.reduce((a,b)=>a+b.wrong,0)}｜漏字：${arr.reduce((a,b)=>a+b.miss,0)}｜多字：${arr.reduce((a,b)=>a+b.extra,0)}</p><p>各科平均：${byHtml}</p><button onclick="showPanel('home')">回首頁</button></div>`}
function renderProgress(){let s=loadStore();let cats=Object.entries(s.stats.byCat||{}).map(([k,v])=>`<div class="listitem"><b>${k}</b> 平均 ${(v.sum/v.n).toFixed(1)}｜作答 ${v.n} 題</div>`).join('')||'尚無紀錄';let reps=(s.stats.reports||[]).reverse().map(r=>`<div class="listitem">${r.date}<br>${esc(r.mode)}｜${r.score}｜${r.pass?'PASS':'未通過'}</div>`).join('')||'尚無成績單';$('progressContent').innerHTML=`<div class="grid stats"><div class="statcard">累積作答<br><b>${s.stats.total}</b></div><div class="statcard">平均<br><b>${s.stats.total?(s.stats.sum/s.stats.total).toFixed(1):0}</b></div><div class="statcard">錯題庫<br><b>${s.wrong.length}</b></div></div><h3>各科表現</h3>${cats}<h3>最近成績單</h3>${reps}<button onclick="if(confirm('確定清空全部學習紀錄？')){localStorage.removeItem('quizV3');renderProgress();renderHome()}">清空紀錄</button>`}
function renderSearch(){let v=($('searchBox')?.value||'').trim();let list=v?QUESTIONS.filter(q=>(q.q+q.a+q.categoryName).includes(v)).slice(0,50):QUESTIONS.slice(0,20);$('searchResult').innerHTML=list.map(q=>`<div class="listitem"><b>${q.categoryName} ${q.number}</b> ${esc(q.q)}<br><small>${esc(q.a)}</small><br><button onclick="startQuiz('單題練習',[QUESTIONS.find(x=>x.id===${q.id})],false)">練這題</button></div>`).join('')}
let game={blocks:3,score:0,combo:0,q:null};function newGameQuestion(){if(!QUESTIONS.length)return;game.q=QUESTIONS[Math.floor(Math.random()*QUESTIONS.length)];$('gameQMeta').textContent=`${game.q.categoryName} 第${game.q.number}題`;$('gameQ').textContent=game.q.q;$('gameAns').value='';$('gameResult').classList.add('hidden');renderGame()}
function renderGame(){$('blocks').textContent=game.blocks;$('gameScore').textContent=game.score;$('combo').textContent=game.combo}
function consumeBlock(){if(game.blocks<=0){alert('方塊不足，請先回答題目取得方塊');return}game.blocks--;game.score+=10;renderGame()}
function gradeGame(){let r=diffAnswer($('gameAns').value,game.q.a);let gain=r.score===100?3:1;game.blocks+=gain;game.combo=r.score===100?game.combo+1:0;game.score+=Math.round(r.score);addWrongIfNeeded(game.q,r.score);$('gameResult').classList.remove('hidden');$('gameResult').innerHTML=`<h3>${r.score.toFixed(1)}分，獲得 ${gain} 個方塊</h3><div class="diff">${r.html}</div>`;renderGame();newGameQuestion()}
function addWrongIfNeeded(q,score){if(score<100)addWrong(q)}
