
let QUESTIONS=[];let state={mode:'',set:[],idx:0,exam:null,scores:[],start:0};
const $=id=>document.getElementById(id);
const views=['home','practiceMenu','examMenu','quiz','wrong','stats','game'];
const punct=/[\s，。、「」；：！？,.!?;:()（）\[\]【】『』《》〈〉\-—~～、\n\r\t]/g;
function norm(s){return (s||'').replace(punct,'').replace(/[０-９]/g,d=>String.fromCharCode(d.charCodeAt(0)-65248));}
function esc(s){return (s||'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));}
function loadStore(){return JSON.parse(localStorage.getItem('quizStore')||'{"wrong":[],"fav":[],"stats":{"attempts":0,"totalScore":0,"perfect":0,"byCat":{},"days":{},"reports":[]}}')}
function saveStore(s){localStorage.setItem('quizStore',JSON.stringify(s)); renderDash();}
function showView(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id)); if(id==='home')renderDash();}
function shuffle(a){return [...a].sort(()=>Math.random()-0.5)}
async function init(){try{QUESTIONS=await fetch('questions.json').then(r=>r.json())}catch(e){QUESTIONS=[];alert('題庫載入失敗，請確認 questions.json 已上傳。')}renderDash();showView('home');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}
function renderDash(){let s=loadStore().stats;let today=new Date().toISOString().slice(0,10);$('dashStats').innerHTML=statHTML('累積作答',s.attempts||0)+statHTML('平均分數',s.attempts?((s.totalScore||0)/s.attempts).toFixed(1):0)+statHTML('滿分題數',s.perfect||0)+statHTML('今日作答',(s.days&&s.days[today])||0)+statHTML('錯題數',loadStore().wrong.length)}
function statHTML(t,v){return `<div class="stat">${t}<br><b>${v}</b></div>`}
function byRange(cat,a,b){return QUESTIONS.filter(q=>q.cat===cat&&q.no>=a&&q.no<=b)}
function startSequential(cat,a,b){startSet(byRange(cat,a,b),`${cat} ${a}-${b}`,false)}
function startMixed20(){let pool=[...byRange('陸綱',1,20),...byRange('指參',1,20),...byRange('情報',1,10),...byRange('聯兵營',1,10)];startSet(shuffle(pool).slice(0,20),'混合20題',false)}
function startRandom40(){startSet(shuffle(QUESTIONS).slice(0,40),'全範圍隨機40題',false)}
function startExam(stage,n,pass){startSet(shuffle(QUESTIONS).slice(0,n),`第${stage}階段模擬考`,true,{stage,pass})}
function startSet(set,name,isExam,exam=null){state={mode:name,set,idx:0,exam,scores:[],start:Date.now()};showView('quiz');renderQ();}
function renderQ(){let q=state.set[state.idx];if(!q)return finishExam();$('quizMeta').innerHTML=`${state.mode}｜第 ${state.idx+1}/${state.set.length} 題｜${q.cat}${q.no}`;$('question').textContent=q.q;$('userAnswer').value='';$('gradeResult').innerHTML='';$('answerBox').classList.add('hidden');$('answerBox').textContent='';}
function nextQ(){if(state.idx<state.set.length-1){state.idx++;renderQ()}else if(state.exam)finishExam();}
function prevQ(){if(state.idx>0){state.idx--;renderQ()}}
function diffGrade(answer,user){let a=norm(answer),u=norm(user);let n=a.length,m=u.length;let dp=Array.from({length:n+1},()=>Array(m+1).fill(0));for(let i=0;i<=n;i++)dp[i][0]=i;for(let j=0;j<=m;j++)dp[0][j]=j;for(let i=1;i<=n;i++)for(let j=1;j<=m;j++)dp[i][j]=a[i-1]===u[j-1]?dp[i-1][j-1]:Math.min(dp[i-1][j-1],dp[i-1][j],dp[i][j-1])+1;let i=n,j=m,ops=[];while(i>0||j>0){if(i>0&&j>0&&a[i-1]===u[j-1]){ops.push(['ok',a[i-1]]);i--;j--}else if(i>0&&j>0&&dp[i][j]===dp[i-1][j-1]+1){ops.push(['bad',a[i-1],u[j-1]]);i--;j--}else if(i>0&&dp[i][j]===dp[i-1][j]+1){ops.push(['miss',a[i-1]]);i--}else{ops.push(['extra',u[j-1]]);j--}}ops.reverse();let counts={bad:0,miss:0,extra:0,ok:0};ops.forEach(o=>{counts[o[0]]++});let errors=counts.bad+counts.miss+counts.extra;let score=Math.max(0,100-errors*.5);let html=ops.map(o=>o[0]==='ok'?`<span class="ok">${esc(o[1])}</span>`:o[0]==='bad'?`<span class="bad" title="你寫成：${esc(o[2])}">${esc(o[1])}</span>`:o[0]==='miss'?`<span class="miss">${esc(o[1])}</span>`:`<span class="extra">多:${esc(o[1])}</span>`).join('');return{score,counts,errors,html,cleanAnswer:a,cleanUser:u};}
function gradeCurrent(){let q=state.set[state.idx], user=$('userAnswer').value;let r=diffGrade(q.a,user);$('gradeResult').innerHTML=`<div class="answer"><b>批改結果</b><br>本題分數：${r.score.toFixed(1)}｜錯字：${r.counts.bad}｜漏字：${r.counts.miss}｜多字：${r.counts.extra}<br><br>${r.html}</div>`;record(q,r);state.scores[state.idx]=r.score;if(r.score<100)addWrong(q);return r;}
function revealAnswer(){let q=state.set[state.idx];$('answerBox').classList.remove('hidden');$('answerBox').textContent='標準答案：\n'+q.a+'\n\n出處：'+(q.source||'');}
function record(q,r){let store=loadStore(),s=store.stats;let today=new Date().toISOString().slice(0,10);s.attempts=(s.attempts||0)+1;s.totalScore=(s.totalScore||0)+r.score;if(r.score>=100)s.perfect=(s.perfect||0)+1;s.days=s.days||{};s.days[today]=(s.days[today]||0)+1;s.byCat=s.byCat||{};s.byCat[q.cat]=s.byCat[q.cat]||{n:0,total:0};s.byCat[q.cat].n++;s.byCat[q.cat].total+=r.score;saveStore(store);}
function addWrong(q){let store=loadStore();if(!store.wrong.some(x=>x.id===q.id))store.wrong.push(q);saveStore(store)}
function toggleFavorite(){let q=state.set[state.idx],store=loadStore();let i=store.fav.indexOf(q.id);if(i>=0){store.fav.splice(i,1);alert('已取消收藏')}else{store.fav.push(q.id);alert('已收藏')}saveStore(store)}
function finishExam(){if(!state.exam)return;let answered=state.scores.filter(x=>typeof x==='number');let avg=answered.length?answered.reduce((a,b)=>a+b,0)/state.set.length:0;let pass=avg>=state.exam.pass;let mins=Math.round((Date.now()-state.start)/60000);let report=`${state.mode}\n日期：${new Date().toLocaleString()}\n題數：${state.set.length}\n總成績：${avg.toFixed(1)}\n合格標準：${state.exam.pass}\n判定：${pass?'合格 PASS':'不合格 FAIL'}\n作答時間：約 ${mins} 分鐘`;let store=loadStore();store.stats.reports=store.stats.reports||[];store.stats.reports.unshift(report);store.stats.reports=store.stats.reports.slice(0,10);saveStore(store);$('gradeResult').innerHTML=`<div class="report">${report}</div>`;}
function showWrong(){showView('wrong');let w=loadStore().wrong;$('wrongList').innerHTML=w.length?w.map(q=>`<div class="card"><b>${q.cat}${q.no}</b> ${esc(q.q)}<br><button class="btn" onclick="startSet([QUESTIONS.find(x=>x.id===${q.id})],'錯題重做',false)">重做</button><button class="btn danger" onclick="removeWrong(${q.id});showWrong()">移除</button></div>`).join(''):'目前沒有錯題';}
function removeWrong(id){let st=loadStore();st.wrong=st.wrong.filter(q=>q.id!==id);saveStore(st)}function clearWrong(){if(confirm('確定清空錯題？')){let st=loadStore();st.wrong=[];saveStore(st);showWrong()}}
function showStats(){showView('stats');let st=loadStore(),s=st.stats;let catHtml=Object.entries(s.byCat||{}).map(([k,v])=>statHTML(k+'平均',(v.total/v.n).toFixed(1))).join('');$('statsBox').innerHTML=statHTML('累積作答',s.attempts||0)+statHTML('平均分數',s.attempts?((s.totalScore||0)/s.attempts).toFixed(1):0)+statHTML('滿分題',s.perfect||0)+statHTML('錯題',st.wrong.length)+catHtml;$('reports').innerHTML=(s.reports||[]).map(r=>`<div class="report">${esc(r)}</div>`).join('')||'尚無成績單';}
function resetStats(){if(confirm('確定重置所有統計與錯題？')){localStorage.removeItem('quizStore');showStats();renderDash();}}
// Block game
let game={grid:[],blocks:[],selected:null,score:0,clears:0,q:null};
const SHAPES=[[[1]],[[1,1]],[[1],[1]],[[1,1,1]],[[1],[1],[1]],[[1,1],[1,1]],[[1,0],[1,1]],[[0,1],[1,1]],[[1,1,1],[0,1,0]],[[1,1,0],[0,1,1]],[[0,1,1],[1,1,0]],[[1,1,1],[1,0,0]],[[1,1,1],[0,0,1]]];
function randBlock(){return JSON.parse(JSON.stringify(SHAPES[Math.floor(Math.random()*SHAPES.length)]));}
function startGame(){game={grid:Array(64).fill(0),blocks:[randBlock(),randBlock(),randBlock()],selected:null,score:0,clears:0,q:null};showView('game');renderGame();$('gameQuiz').classList.add('hidden');}
function renderGame(){let b=$('board');b.innerHTML='';game.grid.forEach((v,i)=>{let d=document.createElement('div');d.className='cell '+(v?'filled':'');d.onclick=()=>placeAt(i);b.appendChild(d)});let box=$('blocks');box.innerHTML='';game.blocks.forEach((shape,idx)=>{let el=document.createElement('div');el.className='block '+(game.selected===idx?'selected':'');el.onclick=()=>{game.selected=idx;renderGame()};let rows=shape.length,cols=Math.max(...shape.map(r=>r.length));let mini=document.createElement('div');mini.className='mini';mini.style.gridTemplateColumns=`repeat(${cols},18px)`;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){let m=document.createElement('div');m.className='miniCell '+(shape[r][c]?'on':'off');mini.appendChild(m)}el.appendChild(mini);box.appendChild(el)});$('gameScore').textContent=game.score;$('gameClears').textContent=game.clears;$('gameBlocks').textContent=game.blocks.length;if(game.blocks.length===0)showGameQuiz();}
function canPlace(shape,row,col){for(let r=0;r<shape.length;r++)for(let c=0;c<shape[r].length;c++)if(shape[r][c]){let rr=row+r,cc=col+c;if(rr<0||rr>=8||cc<0||cc>=8||game.grid[rr*8+cc])return false;}return true}
function placeAt(index){if(game.selected===null)return alert('請先選擇方塊');let shape=game.blocks[game.selected],row=Math.floor(index/8),col=index%8;if(!canPlace(shape,row,col))return alert('這裡不能放');for(let r=0;r<shape.length;r++)for(let c=0;c<shape[r].length;c++)if(shape[r][c])game.grid[(row+r)*8+col+c]=1;game.blocks.splice(game.selected,1);game.selected=null;game.score+=10;clearLines();renderGame();}
function clearLines(){let rows=[],cols=[];for(let r=0;r<8;r++)if([...Array(8)].every((_,c)=>game.grid[r*8+c]))rows.push(r);for(let c=0;c<8;c++)if([...Array(8)].every((_,r)=>game.grid[r*8+c]))cols.push(c);rows.forEach(r=>{for(let c=0;c<8;c++)game.grid[r*8+c]=0});cols.forEach(c=>{for(let r=0;r<8;r++)game.grid[r*8+c]=0});let n=rows.length+cols.length;if(n){game.clears+=n;game.score+=n*100;}}
function showGameQuiz(){refreshGameQuestion();$('gameQuiz').classList.remove('hidden');}
function refreshGameQuestion(){game.q=QUESTIONS[Math.floor(Math.random()*QUESTIONS.length)];$('gameQuestion').textContent=`${game.q.cat}${game.q.no}：${game.q.q}`;$('gameAnswer').value='';$('gameGrade').innerHTML='';}
function submitGameAnswer(){let r=diffGrade(game.q.a,$('gameAnswer').value);$('gameGrade').innerHTML=`<div class="answer">分數：${r.score.toFixed(1)}<br>${r.html}</div>`;record(game.q,r);if(r.score<100)addWrong(game.q);let count=r.score>=95?3:r.score>=80?2:1;game.blocks=Array.from({length:count},randBlock);$('gameQuiz').classList.add('hidden');renderGame();}
init();
